URL_AUTH_LOGIN = 'https://stellarburgers.nomoreparties.site/api/auth/login'
URL_AUTH_REGISTER = 'https://stellarburgers.nomoreparties.site/api/auth/register'
URL_AUTH_USER = 'https://stellarburgers.nomoreparties.site/api/auth/user'
URL_INGREDIENTS = 'https://stellarburgers.nomoreparties.site/api/ingredients'
URL_ORDERS = 'https://stellarburgers.nomoreparties.site/api/orders'
URL_ORDERS_ALL = 'https://stellarburgers.nomoreparties.site/api/orders/all'
